### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by be59okuz** [FatihAvdan/metin2-opencv-bot#1]
Traceback (most recent call last):
  File "C:\Users\oguzh\OneDrive\Masaüstü\metin2-opencv-bot-main\main.py", line 318, in <module>
    Test()
  File "C:\Users\oguzh\OneDrive\Masaüstü\metin2-opencv-bot-main\main.py", line 295, in Test
    correctStone = findCorrectStone(wincap,header,stoneTreshold)
  File "C:\Users\oguzh\OneDrive\Masaüstü\metin2-opencv-bot-main\main.py", line 163, in findCorrectStone
    screen = wincap.get_screenshot()
  File "C:\Users\oguzh\OneDrive\Masaüstü\metin2-opencv-bot-main\windowcapture.py", line 49, in get_screenshot
    dataBitMap.CreateCompatibleBitmap(dcObj, self.w, self.h)
win32ui.error: CreateCompatibleDC failed

**Comment by FatihAvdan** [comment]
https://letmegooglethat.com/?q=win32ui.error%3A+CreateCompatibleDC+failed
